#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=batch
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=02:00:00
#SBATCH --output=slurm_output/batch_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

source activate thesis

pip install --upgrade --force-reinstall torch>=2.6 --index-url https://download.pytorch.org/whl/cu121

echo "Checking PyTorch version..."
python -c "import torch; print(f'PyTorch version: {torch.__version__}')"

srun python batch_all.py \
  --input_csv data/debate_sample_terrorist.csv \
  --party VVD \
  --model_7b Qwen/Qwen2.5-7B-Instruct \
  --model_32b /scratch-shared/lsaleh/models/Qwen2.5-32B-Instruct \
  --resume