#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=batch_vvd_test
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=12:00:00
#SBATCH --output=slurm_output/batch_%A.out

module load 2025
module load Anaconda3/2025.06-1
source "$(conda info --base)/etc/profile.d/conda.sh"

conda activate /scratch-shared/lsaleh/.conda/envs/thesis

python batch_all_party_centric.py \
--party VVD \
--model_7b /scratch-shared/lsaleh/models/Qwen2.5-7B-Instruct \
--model_32b /scratch-shared/lsaleh/models/Qwen2.5-32B-Instruct \
--min_tokens 100 \
--debates_csv outputs/debates.csv \
--cmp_manifest_csv /outputs/cmp_manifest.csv
