#!/bin/bash
#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=incSummary
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=02:00:00
#SBATCH --output=slurm_output/extract_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

source activate thesis

srun python extract.py \
  --input_csv outputs/incr_summary_debate_terrorist.csv \
  --output_csv outputs/extracted_rows.csv \
  --output_claims_csv outputs/extracted_claims.csv \
  --model_name Qwen/Qwen2.5-72B-Instruct \
  --target_party VVD
