#!/bin/bash
#SBATCH --job-name=conda_env
#SBATCH --output=slurm_output/fix_env_%A.out
#SBATCH --time=01:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G

set -euo pipefail

module load 2025
module load Anaconda3/2025.06-1
source "$(conda info --base)/etc/profile.d/conda.sh"

conda activate /scratch-shared/lsaleh/.conda/envs/thesis

conda install -y -c pytorch -c nvidia pytorch=2.4.* pytorch-cuda=12.1

python -c "import torch, transformers; print(torch.__version__); print(torch.cuda.is_available())"