#!/bin/bash
#SBATCH --job-name=conda_env
#SBATCH --output=logs/conda_env.out
#SBATCH --error=logs/conda_env.err
#SBATCH --time=01:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G

module load 2025
module load Anaconda3/2025.06-1

source $(conda info --base)/etc/profile.d/conda.sh

export CONDA_ENVS_PATH=/scratch-shared/lsaleh/.conda/envs
export HF_HOME=/scratch-shared/lsaleh/.cache/huggingface
export TRANSFORMERS_CACHE=$HF_HOME
export HF_DATASETS_CACHE=$HF_HOME

cd ~/thesis

conda env create -f env.yml