#!/bin/bash
#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=normalize
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=02:00:00
#SBATCH --output=slurm_output/norm_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

source activate thesis

srun python normalize.py \
  --claims_csv output/VVDdebate_sample_terrorist_20260401_112625_claims.csv \
  --debates_csv data/debate_sample_terrorist.csv \
  --summaries_csv summaries/debate_sample_terrorist_summary_20260401_112744.csv \
  --output_dir outputs/ \
  --model_name Qwen/Qwen2.5-7B-Instruct \
  --add_timestamp