#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=mani_norm
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=02:00:00
#SBATCH --output=slurm_output/mani_norm_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

srun python normalize_manifesto.py \
  --manifesto_dir manifesto \
  --output_dir outputs/manifesto \
  --party all \
  --model_name /scratch-shared/lsaleh/models/Qwen2.5-32B-Instruct