#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=normalize
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=02:00:00
#SBATCH --output=slurm_output/norm_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

srun python normalize.py \
  --claims_csv outputs/extracted/VVD_claims.csv \
  --debates_csv data/debate_sample_terrorist.csv \
  --summaries_csv outputs/summaries/.combined_summaries_temp.csv \
  --output_dir outputs/normalized \
  --party VVD \
  --model_name /scratch-shared/lsaleh/models/Qwen2.5-32B-Instruct