#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=incSummary
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=02:00:00
#SBATCH --output=slurm_output/inc_summary_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

source activate thesis

srun python incr_summary.py \
  --input_csv data/local_kpa_claims.csv \
  --output_csv outputs/sample_with_incremental_summary.csv \
  --model_name meta-llama/Llama-3.1-8B-Instruct